### ISSUE TITLE
Text data analysis

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#10]
1. Get the Language Distribution using `https://github.com/flairNLP/flair`

2. 
* No Language => Category
* A language => Move onto step 3

3. Get Nr of Words distribution. A histogram of the number of words for each sample in the column (don't bother linking this methodology to the language for now, though we might have to in the future for non indo-european languages)

4. Get Word Distribution. A histogram with the nr of occurrences for every word. Cap this histogram at e.g. the 1000 most common words.

5.
Determine "Rich Text" vs "Short Text" based on some heuristic using the above. Say:

if len(word distribution) > 500 and mean(nr of words) > 5 THEN "Rich Text" else "Short Text"

Add the types as described in #11 first.

**Comment by George3d6** [comment]
@maximlopin is there still some work that needs to be done on this ?

**Comment by maximlopin** [comment]
resolved by https://github.com/mindsdb/mindsdb_native/pull/28
