### ISSUE TITLE
Existing of column with name 'id' in dataset make bad predictor

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_native#102]
* Mindsdb version: last staging
* Lightwood version: 0.34 

For example let take 'home_rentals' dataset and let train predictor to predict 'rental_price'. I made test of three cases:
1. train on data 'as is', without any changes. I got right results.
2. train on data with serial column with name not equal to 'id'. In this case results good too.
3. train on data with serial column with name 'id'. In this case results absolutely bad. 'rental_price' in prediction results in most cases is negative. min/max values looks like random values.

**Comment by George3d6** [comment]
This is likely happening due to `id` not being correctly identified as a `foreign_key` or not being properly removed by the `DataCleaner`

**Comment by George3d6** [comment]
Should be fixed by #103
