### ISSUE TITLE
Allow external data split

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#104]
Add a way of providing an external data split to mindsdb via the `advanced_args`

This should be done by having an advanced_arg called something like `data_split_indexes` that is a dictionary with 3 lists of indexes:

* `validation_indexes`
* `train_indexes`
* `test_indexes`

The best way to impl this is probably just to add this custom splitting behavior to the `DataSplitter`

**Comment by maximlopin** [comment]
resolved by https://github.com/mindsdb/mindsdb_native/pull/108
