### ISSUE TITLE
Add failure state for models

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#105]
We need to allow models (lightwood models for now, but any models in the future) to "fail" during the `ModelAnalyzer` phase.

This means that, if a model is performing really poorly, instead of giving it to the user to make predictions, mindsdb_native should deem it "unusable" instead and throw and error if a `.predict` call is tried + inform the user about this using a final `error` log.

We should have an advanced argument that allows these "failed" models to still be used in `.predict` calls in the rare cases where this might be necessary or desirable for debugging.

Some "easy" ways to determine failure, we can look at various conditions on the validation data inside the `ModelAnalysis` phase:

1. Accuracy is == to random
2. The target is only positive but some results are negative (or vice versa)

**Comment by maximlopin** [comment]
done: https://github.com/mindsdb/mindsdb_native/pull/228
