### ISSUE TITLE
Wrong column type detection

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_native#112]
Same dataset as in issue #111
[test.zip](https://github.com/mindsdb/mindsdb_native/files/5062415/test.zip)
Analysis define type of column 'arrstr' as 'Categorical/Category'. But each value in this column unique, better will be type 'Text', untill we dont support Text/Array.

**Comment by maximlopin** [comment]
this behaviour is expected: https://github.com/mindsdb/mindsdb_native/blob/staging/mindsdb_native/libs/phases/type_deductor/type_deductor.py#L245
