### ISSUE TITLE
ID column is not correctly identified as such

### ISSUE THREAD

**Issue by paxcema** [mindsdb/mindsdb_native#120]
**Your Environment**

* Python version: 3.6.11
* Operating system: Ubuntu 16.04
* Mindsdb native version: 2.3.0
* Additional info if applicable:

**Please describe your issue and how we can replicate it**
For the `automobile_insurance` dataset, column `'Customer'` is an ID column (8220 different values for 8220 rows), however it is not identified as such which results in creating and training an unnecessarily big autoencoder.

**Comment by maximlopin** [comment]
A few thoughts:

Here's the distribution of letters in the `'Customer'` column, we can try doing something with this information to identify it as ID:
`Counter({'7': 3866, '9': 3842, '5': 3842, '3': 3839, '8': 3824, '6': 3801, '4': 3771, '1': 3766, '2': 3688, '0': 3172, 'W': 730, 'M': 708, 'E': 707, 'C': 706, 'F': 706, 'P': 703, 'L': 703, 'Z': 702, 'G': 700, 'N': 700, 'U': 698, 'X': 698, 'B': 694, 'H': 694, 'Q': 693, 'S': 692, 'Y': 689, 'K': 684, 'O': 673, 'V': 672, 'A': 671, 'D': 670, 'R': 665, 'I': 662, 'T': 657, 'J': 650, 'o': 16})`

- `scipy.entorpy` might be useful for measuring "randomness" of the distribution above.
- It's probably better to take the position (index) of each character of ID to account somehow.

**Comment by maximlopin** [comment]
resolved by https://github.com/mindsdb/mindsdb_native/pull/124
