### ISSUE TITLE
Timestamps older than Unix epoch

### ISSUE THREAD

**Issue by paxcema** [mindsdb/mindsdb_native#121]
**Your Environment**

* Python version: 3.6.11
* Operating system: Ubuntu 16.04
* Mindsdb native version: 2.3.0
* Additional info if applicable:

**Please describe your issue and how we can replicate it**

Discovered while analyzing the dataset mentioned [here](https://github.com/mindsdb/mindsdb/issues/648). Basically, all date timestamps prior to the Unix epoch (Jan 1st 1970) are transformed by pandas to very big negative values in this [line](https://github.com/mindsdb/mindsdb_native/blob/stable/mindsdb_native/libs/phases/data_transformer/data_transformer.py#L60) of code, which affects network stability downstream.

**Comment by George3d6** [comment]
We should add a test with older date times and fix this.

Ideally times before Jan 1st 1970 should just be negative values, e.g. `1969-12-31 23:59:59` becomes `-1`.

**Comment by ilia-tsyplenkov** [comment]
> We should add a test with older date times and fix this.
> 
> Ideally times before Jan 1st 1970 should just be negative values, e.g. `1969-12-31 23:59:59` becomes `-1`.

it is present in pandas:
```
>>> import pandas as pd
>>> 
>>> 
>>> 
>>> dt = "1969-12-31 23:59:59"
>>> dt = pd.to_datetime(dt, errors='coerce')
>>> dt.timestamp()
-1.0
>>> dt = "1968-12-31 23:59:59"
>>> dt = pd.to_datetime(dt, errors='coerce')
>>> dt.timestamp()
-31536001.0
```

**Comment by ilia-tsyplenkov** [comment]
I don't think that we need to proceed with this issue, since parent issue is not reproducible anymore (I've checked it) @paxcema could you please suggest?

**Comment by paxcema** [comment]
The sinusoidal mode in Lightwood's datetime encoder seems to be working fine for normalizing any timestamp, so I think we can close this for now.
