### ISSUE TITLE
current MSSQL driver cant fetch big data

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_native#130]
* Python version: 3.6.9
* Operating system: ubuntu
* Mindsdb version: last staging
* Additional info if applicable: pytds==1.10.0

I have troubles when creating predictor with mssql datasource. Reason in `pytds`. This library raise `ClosedConnectionError('Server closed connection',)` if returned results is bigger then some value.
I used regular 'home_rentals' dataset, saved as table in mssql. If i try make datasource from all rows, then i will get error. If i make datasource from, for example, 1000 rows, then it success created. Or i can make datasource from 3-4 columns of all rows, it will be successful too. If i use `pymssql` instead of `pytds`, then all work well on full dataset. I tried find some parameter of `pytds` to fix this issue, but not find it. I know `pytds` was chosen as pure-python lib to make installer build easer, but may be it exists alternative for it?

**Comment by George3d6** [comment]
I guess we could have a try/except import and when people install the `extra_datasource` version of mindsdb/mindsdb_native we can use a different driver.

**Comment by George3d6** [comment]
Fixed by swtiching drivers.
