### ISSUE TITLE
Use balanced_accuracy to determine "failed" category predicting models

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#132]
Mindsdb targets balanced_accuracy instead of normal accuracy for models predicting categories, thus the decision to allow a model to fail should be based on the balanced_accuracy and the "better than random" should be determine based on that (might even make the determination easier, since I guess it would just be 1/nr_of_classes, but maybe I'm wrong here)

**Comment by maximlopin** [comment]
resolved by https://github.com/mindsdb/mindsdb_native/pull/135
