### ISSUE TITLE
Rename `foreign_key` to `identifier`

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#136]
Identifier expresses the role of the foreign_key value as it stands at the moment a bit better.

Identifier columns should consist of an object with two values:

```
{
'name': {name of column that is an identifier}
'type': {the type of identifier, e.g. unique_id, foreign_key, hash... etc}
}
```

We don't have to implement all the type detection at once though.

**Comment by maximlopin** [comment]
Maybe identifier should be a new type (with subtypes like unique_id, hash, ...)?
Because in order to know if a column is an identifier we compute some stats and computations like this probably should belong to TypeDeductor/DataAnalyzer phases.

**Comment by George3d6** [comment]
Hmh, good point, might be ideal. Unless we already use the type for foreign key detection. If we don't feel free to make it a type and have it as:

`Data_type == identifier` -> `subtypes -> [unique identifier, foreign key]`

**Comment by maximlopin** [comment]
resolved by https://github.com/mindsdb/mindsdb_native/pull/144
