### ISSUE TITLE
model['data_analysis_v2'] should contains only fields from datasource

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_native#172]
lightwood version 0.41.0
MindsDB_native version 2.9.0

At this moment `model['data_analysis_v2']` contains additionally 'columns_to_ignore' and 'train_std_dev'

**Comment by George3d6** [comment]
@StpMax why is this an issue?

**Comment by StpMax** [comment]
If forget about `model['data_analisys']` then only one way to get list of model columns can be `[x for x in model['data_analysis_v2'].keys() if x not in ['columns_to_ignore', 'train_std_dev']]`. That not durable: i found out about 'train_std_dev' only when got erorr in console `Error: cant convert type Int of column train_std_dev to clickhouse type`. Same for 'columns_to_ignore'.

I see here two solutions:
1. never add new keys to model['data_analisys']. It must contain datasource fields + 'columns_to_ignore' + 'train_std_dev'
2. change struct to 
```
model['data_analisys_v2'] = {
    'columns': {a: {}, b: {}, c: {}},
    'columns_to_ignore': {},
    'train_std_dev': {}
}
```

**Comment by George3d6** [comment]
data_analysis is no longer used in mindsdb, so closing this.
