### ISSUE TITLE
Alias for numerical categorical columns

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#174]
We should alias numerical columns that we treat as categorical when we log them and display them in Scout with something like `Numerical (Low Granularity)` instead of `Categorical`, @torrmal proposed this for user-reassurance reasons, so that users don't think we miss-detected the type just because internally it makes more sense to treat them as categories.

**Comment by maximlopin** [comment]
done: https://github.com/mindsdb/mindsdb_native/pull/267
