### ISSUE TITLE
Mindsdb converting floats to integer

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#179]
A bug was reported (without the dataset) where the behavior described was:

A column containing floats had an integer in it, resulting in mindsdb auto-detecting the type as integer and truncating the floats to integer.

The behavior here should be opposite, in that Mindsdb should detect float in a column containing a mix of the two types and convert integers to floats.

We should investigate this fairly soon.

**Comment by maximlopin** [comment]
https://github.com/mindsdb/mindsdb_native/pull/185
