### ISSUE TITLE
Don't deploy the sklearn mixer for short training times

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#216]
When the user specified "stop training in" we should have a witter methodology for selecting the mixers:

First, we should have a value like `reasonable_training_time`, let's say this is:

`reasonable_training_time = len(input_data) * nr_columns / 20` (seconds)

For example, this value would be 160 seconds for home rentals.

If `stop_training_after > reasonable_training_time`:
a) Train all mixers
b) Pass `stop_training_after/2` as the stop training time to the NN mixer (assuming sklearn and booster will take an equal amount of time)

If `reasonable_training_time/10 < stop_training_after < reasonable_training_time` we should:
a) Only train the NN mixer
b) pass `stop_training_after` as the stop training value for the NN mixer

If `reasonable_training_time/10 > stop_training_after`:
a) Only train a very quick mixer, such as the booster mixer

Note: Might require reimplementing the booster mixer or some other mixer that is quick to train.

**Comment by maximlopin** [comment]
resolved by https://github.com/mindsdb/mindsdb_native/pull/229
