### ISSUE TITLE
Don't crash if a singer mixer fails to train

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#217]
If a single mixer fails to train, mindsdb should keep going instead of crashing, as long as at least one lightwood model can train to completion we should be fine.

Granted, this would really hamper finding bugs, so it should be placed behind some optional flag that is only enabled when Mindsdb is running in "user" mode. Any ideas how we can do that ?

**Comment by maximlopin** [comment]
resolved by https://github.com/mindsdb/mindsdb_native/pull/228
