### ISSUE TITLE
Replace phase unittest with callback breakpoints

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#225]
The current unit tests for the phases are inefficient and hard to maintain.

Also, since we have to create the transaction data manually  they are very "conservative" in what they check and can be unrealistic.

We should instead (using breakpoint callbacks) just run mindsdb end to end with a few datasets and do a validation of the lmd & hmd at each phase.

**Comment by maximlopin** [comment]
breakpoints are now used but without callbacks https://github.com/mindsdb/mindsdb_native/pull/244
