### ISSUE TITLE
TransactionOutputRow wrong behavior for time series 

### ISSUE THREAD

**Issue by paxcema** [mindsdb/mindsdb_native#238]
Using [this](https://github.com/mindsdb/mindsdb_native/blob/stable/docs/examples/time_series/mall_traffic/train.py) example, but with `nr_predictions = 3 > 1`, we have wrong behavior in both `.explain()` and `.summarize()` methods of the `TransactionOutputRow` class:

```python
>>> forecast[10].summarize()
"* We are 99.25% confident the value of "people_count" is [96, 97, 88] *"

>>> forecast[10].explain()
{'people_count': {'predicted_value': [96, 97, 88], 'confidence': 0.9925, 'prediction_quality': 'very confident', 'important_missing_information': []}}
```

**Comment by maximlopin** [comment]
done: https://github.com/mindsdb/mindsdb_native/pull/246
