### ISSUE TITLE
Remove ludwig

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#257]
### Interface

* Remove `backend` argument and it's parsing as part of `get_model_data` + any other usage
* Remove ludwig dependencies and ludwig setup

### Internally

* `backends` can be removed
* ModelInterface becomes what is now `lightwood.py`
* Any sort of column "cleaning" for luwdig, if still done, should be remove

### Docs

@ZoranPandovski can you remove all references to ludwig

**Comment by maximlopin** [comment]
done: https://github.com/mindsdb/mindsdb_native/pull/275
