### ISSUE TITLE
Remove "what would the prediction be without x"

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#258]
Currently in `transaction.py` and in the output row and output list we have a lot of logic around determining what a prediction would look like if a given column was unavailable, we should remove this logic and the arguments and outputs associated with it.

Reasons are many and boil down to it working poorly and being poorly understood internally and by users.

This will also save a lot of time when predicting and reduce code complexity.

**Comment by maximlopin** [comment]
done: https://github.com/mindsdb/mindsdb_native/pull/271
