### ISSUE TITLE
Add Microsoft SQL database credentials

### ISSUE THREAD

**Issue by maximlopin** [mindsdb/mindsdb_native#263]
- add Microsoft SQL database to credentials
- add tests for it

**Comment by George3d6** [comment]
I will try to setup a MS SQL Database via AWS for this one. @StpMax what "extras" do we need for mindsdb to integrate with and publish models to MS SQL ?

**Comment by StpMax** [comment]
[described here](https://drive.google.com/file/d/1PeVZDRMBng2PrW7-u3d-gdjJyN7Ooe6p/view?usp=sharing)

**Comment by George3d6** [comment]
Max got the machine running: https://github.com/mindsdb/mindsdb_server_enterprise/blob/master/database_testing_env/credentials.json

**Comment by George3d6** [comment]
Added
