### ISSUE TITLE
Different confidence_range for query as list and DataFrame

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_native#288]
Used last staging of mindsdb/native/lightwood.

This issue is of https://github.com/mindsdb/mindsdb/issues/763

Prediction return different confidence_range if in Predictor(when_data) use list or pandas.DataFrame. Often prediction result is out of confidence_range if when_data=DataFrame.

Short example to reproduce:
```
from mindsdb_native import Predictor, FileDS
from pandas import DataFrame as df

ds = FileDS('us_consumption/data.csv')
p = Predictor(name='usc_test1')
p.learn(from_data=ds, to_predict=['Consumption'])

p.predict(when_data={"Income": 1.2, "Savings": 3.182923657, "Unemployment": 0.2, "T": "2020-10-10"})[0].as_dict()
p.predict(when_data=df([{"Income": 1.2, "Savings": 3.182923657, "Unemployment": 0.2, "T": "2020-10-10"}]))[0].as_dict()
```
first result is: `{'T': 1602288000.0, 'Consumption': 1.03305039970698, 'Income': 1.2, 'Production': None, 'Savings': 3.182923657, 'Unemployment': 0.2, '__observed_Consumption': None, 'Consumption_model_confidence': 0.0, 'Consumption_confidence_range': [0.6986246106239531, 1.3674761887900069], 'Consumption_confidence': 0.78}`

second: `{'Income': 1.2, 'Savings': 3.182923657, 'Unemployment': 0.2, 'T': 1602288000.0, 'Consumption': 1.03305039970698, 'Production': None, '__observed_Consumption': None, 'Consumption_model_confidence': 0.0, 'Consumption_confidence_range': [1.0440104059754802, 1.712861984141534], 'Consumption_confidence': 0.78}`

**Comment by paxcema** [comment]
Good catch Max! This was happening because the `when_data` data frame had a different column order from what the conformal predictor expected, so the bounds in the second case were incorrect.
