### ISSUE TITLE
Make sure lock is explicitly removed before closing

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#29]
If there is a crash, in some situations, the lock file might remain open and the lock won't be removed.

We can fix this in two ways:

a) Add a try/except/finally to everything in functional.py and everything in controllers.py that uses a lock.

b) Add an atexit to everything mentioned above

Option `a` is annoying because we'd loss the crash logs and would have to add custom code (using traceback) to recover them.

Option `b` seems fairly good actually, but I don't know, maybe I'm missing something.

**Comment by btseytlin** [comment]
> we'd loss the crash logs and would have to add custom code (using traceback) to recover them.

It's not true, just reraise the exception and no logs are lost

**Comment by George3d6** [comment]
@btseytlin are you sure ? I believe we need the traceback as per @maximlopin current implementation.

If you are sure this is not the case and we find the time we should discuss it in order to simplify the code, for now I will close this issue though, as @maximlopin implementation is enough for our current needs.
