### ISSUE TITLE
Track exceptions through Sentry

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/mindsdb_native#310]
We should enable automatic reporting of exceptions through [Sentry](https://docs.sentry.io/platforms/python/) as a test phase firstly through mindsdb_native.

**Comment by George3d6** [comment]
@ZoranPandovski This should be an issue in `mindsdb`, we can catch native exceptions there.

Native/lightwood should be kept as minimal as possible, which means I'd rather not add these kind of feature in them.

Even the original check for updates should be in mindsdb with hindsight, but now it's too late and too annoying to move, thus it's here instead.
