### ISSUE TITLE
Don't rely on confidence ranges from lightwood

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#328]
Go back to using r2 score for comparing lightwood modles, because those will no longer return numerical ranges, since that is now being handled fairly well by nonconformist.

**Comment by maximlopin** [comment]
already using r2_score: https://github.com/mindsdb/mindsdb_native/blob/staging/mindsdb_native/libs/phases/model_interface/lightwood_backend.py#L419
