### ISSUE TITLE
Wrong CSV parsing

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_native#347]
Last staging of all.

subset of CSV:
```
PronounceGIF
"With a hard ""g,"" like ""gift"""
```
On upload this CSV i get error here: https://github.com/mindsdb/mindsdb_native/blob/stable/mindsdb_native/libs/data_sources/file_ds.py#L79
reason is `len(file_list_data) != len(col_map)`
```
len(file_list_data[1]) == 2  # ['"With a hard ""g', '"" like ""gift"""']
len(col_map) = 1
```
Full CSV:
[Cleaned.zip](https://github.com/mindsdb/mindsdb_native/files/5666230/Cleaned.zip)

**Comment by maximlopin** [comment]
I dont think there is an easy way to support values like `"With a hard ""g', '"" like ""gift"""` because it's not a valid CSV

**Comment by StpMax** [comment]
Why it is not valid? When i open CSV in LibreOffice it shows correct:
![image](https://user-images.githubusercontent.com/4068133/102102578-e44d9800-3e23-11eb-9523-37f35c84d464.png)
Im sure Excel will show it too

**Comment by StpMax** [comment]
Here is CSV escape reference:
https://tools.ietf.org/html/rfc4180#section-2
