### ISSUE TITLE
Negative values for column importance.

### ISSUE THREAD

**Issue by Ricram2** [mindsdb/mindsdb_native#36]
**Please describe your issue and how we can replicate it*

Dataset: African Crisis.
Model: 
[afr_year.zip](https://github.com/mindsdb/mindsdb_native/files/4866261/afr_year.zip)

![image](https://user-images.githubusercontent.com/24927430/86401971-b78c3680-bc70-11ea-84d2-b7098518d12e.png)

```
...
   {
            "column_name":"banking_crisis",
            "importance_score":-1.0,
            "data_type":"Categorical",
            "data_type_distribution":{
               "type":"categorical",
               "x":[
                  "Categorical"
               ],
               "y":[
                  1044
               ]
            },
...
```

issue: we are not supposed to have negative values.

**Comment by maximlopin** [comment]
resolved by https://github.com/mindsdb/mindsdb_native/pull/100
