### ISSUE TITLE
mindsdb_native vs mindsdb

### ISSUE THREAD

**Issue by abitrolly** [mindsdb/mindsdb_native#362]
I see changes in repo organization. Now there is `mindsdb` and `mindsdb_native`. It would be nice to get a better description how do they play together.

**Comment by George3d6** [comment]
@abitrolly 

`mindsdb` can be thought of as a "wrapper" over `mindsdb_native` that adds:

* An HTTP API
* A GUI for easy usage and visualization (Scout)
* The ability to integrate mindsdb into various databases (mysql, mariadb, postgres, mongo, clickhouse) and create + query models from within the databases
* Key-Value based storage for your datasource (ranging from files to queries on your databases)

`mindsdb_native` does what the old `mindsdb` repo did, i.e. all the autoML and explainability stuff.

**Comment by abitrolly** [comment]
Thanks. That fills the spot. Might worth updating `README.md` for one of the projects.
