### ISSUE TITLE
Test split for time series should have at least nr_predictions per group by

### ISSUE THREAD

**Issue by paxcema** [mindsdb/mindsdb_native#374]
When training a predictor for time series that specifies `nr_predictions=n`, the `test_df` generated by Native should have at least `n` rows per each `group_by`, otherwise computing accuracy in Lightwood cannot be done for that timestep.

**Comment by George3d6** [comment]
Since a solution in lightwood exists I'm going to close this, I think it's essentially and edge case and solving it would be fairly annoying and result in very small training sets.
