### ISSUE TITLE
Stop relying on lightwood directly

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#383]
The nonconformist implementation should, if possible, just use the `ModelInterface`'s predict/learn methods instead of relying on lightwood directly.

**Comment by paxcema** [comment]
Ok, this is trickier than I thought. The way I see it, we need to instance a `PredictTransaction` while a `LearnTransaction` is going on... but then we run into an active `MDBLock()`

@George3d6 thoughts on how to proceed?

**Comment by paxcema** [comment]
Addressed in #377.
