### ISSUE TITLE
Same confidence for any predictions

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_native#393]
* Python version: 3.6.9
* Mindsdb version: last staging
* Additional info if applicable: no gpu

At this moment i get same confidence for any prediction, no matter wich crazy values i use as input. For example, that prediction for new trained 'concrete_scrength' dataset:
```
{'id': [None], 'cement': [None], 'slag': [None], 'flyAsh': [None], 'water': [4567486.0], 'superPlasticizer': [None], 'coarseAggregate': [None], 'fineAggregate': [None], 'age': [None], 'concrete_strength': [14.99127645671796], '__observed_concrete_strength': [None], 'concrete_strength_confidence': [0.93], 'concrete_strength_confidence_range': [[7.245124749459071, 22.73742816397685]]}
```

**Comment by paxcema** [comment]
I'll look into it. I get the point about confidence not changing for crazy values, however I see that the reported prediction does indeed fall within bounds, so I don't see the issue that the title describes.

**Comment by George3d6** [comment]
Are you using the latest lightwood @StpMax ?

**Comment by StpMax** [comment]
@George3d6 yes, im sure mindsdb, mindsdb_native and lightwood is latest staging.
@paxcema you right, sorry. Header is not relevant. I will edit issue now.

**Comment by StpMax** [comment]
@paxcema here is two predictions: first with condition values from real data, second with random values. Both confidence = 93%. For any prediction i get same confidence.
![image](https://user-images.githubusercontent.com/4068133/104888877-476fa480-5965-11eb-84a5-32d7209a55ce.png)

**Comment by paxcema** [comment]
I'll attempt to solve this through a standard normalizer (for when the self-aware network is not triggered), which will hopefully fix this. Keep you posted.

**Comment by George3d6** [comment]
@paxcema any time to look into this?

**Comment by paxcema** [comment]
Not yet, but it ties nicely into [#1116](https://github.com/mindsdb/mindsdb/issues/1116) so I'll probably work on this next week at some point.

EDIT: As an update, KNN normalizers don't seem that enticing, so I'm opting for our self-aware network to be the only normalizer, and active at all times. This would imply confidence (and bounds) estimated independently for each data point. I'll have to do some moving around in Lightwood, will keep you posted.

**Comment by George3d6** [comment]
When `self.stop_selfaware_training` is set to `True`.

Instead of stopping to train the selfaware, we should simply decouple the slefware's loss from the models' loss, so that it doesn't bring down the models' accuracy.

For lightGBM we should simply use the probability distribtuion that gives for categorical, unsure for numerical.

**Comment by George3d6** [comment]
We have to make sure that noncoformist takes into account the `loss_confidences` values outputs by lightwood.

**Comment by George3d6** [comment]
Bug is in lightwood, so closing here.
