### ISSUE TITLE
Column names for nested entities

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#438]
Currently unnesting is happening in the `DataExtractor` phase, this is good because unnesting => in a bunch of metadata being stored and it's controlled in part by the user's argument, which we don't have on the datasource interface and which might make the interface cumbersome if we add them.

However we have to find a (quick) way to extract column names from datasources containing nested entities, and this happens in the datasource, and for various reasons should stay in the datasource.

Quick solution I'm thinking of: unnest first ~100-200 rows of the resulting dataframe in the datasource directly (with limit for databases that support it) and generate the column map from that.

Not ideal, especially since it will => in duplicate functionality between the extractor and the datasource.

The alternative however is merging the `DataExtractor` (or at least part of it's capabilities) into the datasource, and that comes with it's own host of issues.

**Comment by maximlopin** [comment]
https://github.com/mindsdb/mindsdb_native/pull/439
