### ISSUE TITLE
Some of the 54 benchmark datasets fail

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#479]
Some benchmark datasets fail to run, I previously overestimate this number, will update here with more detials.

This might be an issue with the benchmarks, and I'm dearly hoping it is so, but I'm uncertain this is the case.

We need to investigate more.

1. Run benchmarks locally and see how many of them pass (WIP overnight, and potentially over the weekend, depending on how long it takes)
2. Figure out if sources of failures are in benchmarks or native
3. For source of failures in native transalte into specific issues

**Comment by maximlopin** [comment]
cornell_moview_review - takes forever
metro_traffic_ts - exception
stanford_movie_review - takes forever
travel_insurance - takes forever
tripadvisor - takes forever
tripadvisor_binary - takes forever
used_car_price - exception
