### ISSUE TITLE
Make DataTransformer phase run before DataSplitter

### ISSUE THREAD

**Issue by btseytlin** [mindsdb/mindsdb_native#52]
It seems like we could run most if not all of the DataTransformer work before splitting into train/test/validation and the code will be much cleaner.

I am not sure though about the "Unbias dataset for training logic" here:
https://github.com/mindsdb/mindsdb_native/blob/stable/mindsdb_native/libs/phases/data_transformer/data_transformer.py#L126
I don't understand any of it, maybe it's dependant on the splits.

**Comment by George3d6** [comment]
@btseytlin this becomes a problem when you consider the `ludwig` backend requires duplication to be done in all datasets for equal weighting, but the ModelAnalyzer only requries duplciation in the `validation` datasets (though we might change that to something fancier in the future or even just move the `ModelAnalyzer` to lightwood entirely.

Also, we might want to "transform" other things in one of the datasets but no the other

**Comment by btseytlin** [comment]
I can think of some things that we might want to only do on train, but not on test: data augmentation for images.
But most of the work in data transformer is not like this, its like converting string numbers to ints, converting dates to the same format, handling nan values, and so on. It is actually data cleaning work

We could do this:

DataExtractor -> DataAnalyzer -> DataCleaner (with all the cleaning logic that is in Transform) -> ...

DataAnalyzer only depends on DataCleaner in the regard that DataCleaner identifies empty columns and signals to ignore them. This can be done in DataAnalyzer too. And then DataCleaner can use the info of DataAnalysis to "smartly" preprocess data.

What do you think?

**Comment by George3d6** [comment]
We need to merge some of the changes in that PR once's there enough time, couldn't merge as it (reasons for can be seen in notion.io)
