### ISSUE TITLE
Find redundant arguments

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#6]
Some arguments may be redundant, especially in the learn and/or predict methods, i.e. maybe they are never used or maybe they are confusing and they should be renamed, or maybe they are currently in the `unstable_parameters_dict` but really they are very important and should be exposed to the user directly.

Let's discuss what they might be in order to clear up the interface before the `2.0.0` release.

**Comment by George3d6** [comment]
We still have to review the `learn` and `predict` commands to see if we can cut some chaff.

@btseytlin and @maximlopin @StpMax @torrmal if anyone wants to make some suggestions now is the time as I will be finalizing those this week.

**Comment by btseytlin** [comment]
I cut everything that I could find in this PR: https://github.com/mindsdb/mindsdb_native/pull/20

**Comment by George3d6** [comment]
After the final PR that I forgot to reference this issue in, I believe the interface is now fully ready for the 2.0 release.
