### ISSUE TITLE
Add "switch" between lightwood stable/staging branches for tests

### ISSUE THREAD

**Issue by maximlopin** [mindsdb/mindsdb_native#61]
https://github.com/mindsdb/mindsdb_native/pull/59

we need a "switch" in mindsdb_native so we can import the staging version of lightwood for running tests.
the PR above is an example of when it's useful: lightwood has a new feature (`TextAutoEncoder`) and we want to use it when it's not at lightwood/stable yet

**Comment by btseytlin** [comment]
The lightwood version is not part of python code so I don't think we can make a switch in code.

I think for development and testing you can just change the requirement to lightwood:staging. Pip allows to install directly from a git repo (https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch).

Then, ideally, you merge lightwood staging into stable first. Then you change the mindsdb native PR that uses lightwood staging back to using lightwood stable. And then you merge mindsdb native

**Comment by George3d6** [comment]
I think there's a way to do without touching the code at all actually. In the `.travis.yml` add something like:

`if branch != stable then pip3 install git+https://github.com/mindsdb/lightwood.git@staging --upgrade`

Right after the principal install, that way this will override the main lightwood version that got installed from pip, no dependencies are reinstalled so it works fairly quickly.

This way we don't modify the setup.py or requirements.txt, but Travis can still run for staging build using the staging for lightwood.

**Comment by maximlopin** [comment]
resolved by https://github.com/mindsdb/mindsdb_native/pull/59
