### ISSUE TITLE
Add new data type and type deduction for multiple categories (tags)

### ISSUE THREAD

**Issue by btseytlin** [mindsdb/mindsdb_native#63]
Basically add ability to do multi-label classification.

Related to: https://github.com/mindsdb/lightwood/issues/203

Example dataset for multi-label classification: https://www.kaggle.com/cryptexcode/mpst-movie-plot-synopses-with-tags

**Comment by George3d6** [comment]
Quick notes on potential issues here:

a) Confusion between multi tags and timeseries when we have something like `1,2,3,4,5,6`
b) Figuring out the difference between Short text and multiple tags, which I think we can solve by a combination of:
* Looking for different combinations of the same words (once we tokenize into words)
* Looking at word density (i.e. `uniqe(words)/sum(len(sentences))`) and setting an arbitrary boundary that "sort of works" much like we do for categories.
