### ISSUE TITLE
DataCleaner issues with ignored column

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#70]
To replicate clone `mindsdb_examples` and run https://github.com/mindsdb/mindsdb-examples/blob/master/benchmarks/cifar_100/video_tutorial.py

However has time to look at this tomorrow please do, if it's a bug that's not specific to just this niche example let's hotfix it into `stable` (assuming it shows up on stable)

**Comment by btseytlin** [comment]
I will take a look at this

**Comment by btseytlin** [comment]
Here's the fix:
https://github.com/mindsdb/mindsdb_native/pull/72

@George3d6 I suggest we merge it to staging for two reasons: 1. staging to stable release is soon next week and 2. some of the tests I have written for this fix are dependant on a thing introduced in staging (transaction being accessible).

We could merge the tiny fix itself separately into stable, and tests separately into staging of course.

**Comment by btseytlin** [comment]
@maximlopin after the fix the example fails with the following error:
```
ValueError: decode is only defined for combine="concat"
```

It seems to me that mindsdb_native uses the `ShortTextEncoder` here for the output variable `class`, for some reason. Could you please take a look at this?

**Comment by George3d6** [comment]
@btseytlin well pointed, it's because the sample is really weird, making an issue.

Likely not to come up in a real situation, but still important.
