### ISSUE TITLE
ModelInterface: "ValueError: month must be in 1..12"

### ISSUE THREAD

**Issue by maximlopin** [mindsdb/mindsdb_native#92]
**To reproduce**
Download this dataset (`covid.csv`):
https://www.kaggle.com/tanmoyx/covid19-patient-precondition-dataset

Run this code:
```
from mindsdb_native import Predictor
pred = Predictor('value_error')
pred.learn(
    from_data='covid.csv',
    to_predict='date_died',
    ignore_columns=['id'],
    advanced_args={'null_values': {'date_died': ['9999-99-99']}, 'debug': True}
)
```
Expected the predictor to successfully train a model, but there is an exception at `ModelInterface` phase: `ValueError: minute must be in 0..59`

**Comment by maximlopin** [comment]
my guess is that the data has dates of format mm/dd/yyyy, and mindsdb expected dd/mm/yyyy, I think we can add user-provided date formats in `advanced_args` and/or date format auto-detection

**Comment by paxcema** [comment]
This [PR](https://github.com/mindsdb/lightwood/pull/323) solves the issue, closing.
