### ISSUE TITLE
Not clear how to read the accuracy of trained model

### ISSUE THREAD

**Issue by Ricram2** [mindsdb/mindsdb_native#97]
After predictor.learn is not clear how can I access the "metadata of the model" i.e Accuracy
I am thinking something like
 
model.accuracy(model) = 0.85

or something a like.

**Comment by torrmal** [comment]
I think we should have a method, in https://github.com/mindsdb/mindsdb_native/blob/stable/mindsdb_native/libs/controllers/predictor.py
.get_metrics()

which should return a dictionary with, r_2 and stuff like that, so that people can also do their own benchmarks

**Comment by torrmal** [comment]
we should pick a set of standard/common metrics per data type

![image](https://user-images.githubusercontent.com/5898506/89324031-75715e80-d63b-11ea-88b6-e30eb6d6eeee.png)

**Comment by paxcema** [comment]
While we implement what @torrmal suggests, I think you can access the training metric by doing `predictor.train_accuracy`.

**Comment by George3d6** [comment]
@torrmal  People can already run their own benchmarks using the `test` function with whatever accuracy function they want

@paxcema @Ricram2  The `train_accuracy` is already provided in `get_model_data` and `get_models` (the `validation_accuracy` is the one that should be used)

Regrading the metrics I think we should stick to (balanced) accuracy for cateogircal and accuracy as defined by % of number between the two quantiles for numerical, that way that can also be a target for the selfaware network and thus confidence becomes much easier to test and explain to the user.
